name: Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run global prettier check
        run: yarn run prettier

      - name: Run linter
        run: yarn run lint

      - name: Run typecheck
        run: yarn run typecheck

      - name: Run tests
        run: yarn run test

      - name: Run tests for storybook
        run: yarn run test:storybook
